// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt76J6ow4-vcilHph2klA7YWYf6z1uGZQ',
    appId: '1:952521403907:web:c10e0c16bb60d6da212836',
    messagingSenderId: '952521403907',
    projectId: 'anri-5e06f',
    authDomain: 'anri-5e06f.firebaseapp.com',
    databaseURL: 'https://anri-5e06f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anri-5e06f.firebasestorage.app',
    measurementId: 'G-MCN1853VH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyJmceo861JmncvuulVg0uixRfiXRZ3KY',
    appId: '1:952521403907:android:63a77de2e9e9d60a212836',
    messagingSenderId: '952521403907',
    projectId: 'anri-5e06f',
    databaseURL: 'https://anri-5e06f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anri-5e06f.firebasestorage.app',
  );
}
